<?php
if ( ! defined( 'ABSPATH' ) ) exit;
$one_delete =
array(
	"post_img" => array("name" => "post_img"),
	"hot" => array("name" => "hot"),
	"cms_top" => array(	"name" => "cms_top"),
	"cat_top" => array("name" => "cat_top"),
	"show" => array("name" => "show"),
	"go_url" => array("name" => "show_url"),
	"direct" => array("name" => "direct"),
	"direct_btn" => array("name" => "direct_btn"),
	"link_inf" => array("name" => "link_inf"),
	"from" => array("name" => "from"),
	"copyright" => array("name" => "copyright"),
	"file_os" => array("name" => "file_os"),
	"file_inf" => array("name" => "file_inf"),
	"small" => array("name" => "small"),
	"product" => array("name" => "product"),
	"pricex" => array("name" => "pricex"),
	"pricey" => array("name" => "pricey"),
	"taourl" => array("name" => "taourl"),
	"discount" => array("name" => "discount"),
	"discounturl" => array("name" => "discounturl"),
	"sites_link" => array("name" => "sites_link"),
	"guide_img" => array("name" => "guide_img"),
	"group_slider_url" => array("name" => "group_slider_url"),
	"header_img" => array("name" => "header_img"),
	"small_img" => array("name" => "small_img"),
	"pr_b" => array("name" => "pr_b"),
	"pr_a" => array("name" => "pr_a"),
	"pr_c" => array("name" => "pr_c"),
	"pr_d" => array("name" => "pr_d"),
	"pr_e" => array("name" => "pr_e"),
	"pr_f" => array("name" => "pr_f"),
	"mark" => array("name" => "mark"),
	"baidu_pan_btn" => array("name" => "baidu_pan_btn"),
	"down_local_btn" => array("name" => "down_local_btn"),
	"down_official_btn" => array("name" => "down_official_btn"),
	"sidebar_l" => array("name" => "sidebar_l"),
	"menu_post" => array("name" => "menu_post"),
	"no_abstract" => array("name" => "no_abstract"),
	"slide_title" => array("name" => "slide_title"),
	"down_link_much" => array("name" => "down_link_much"),
	"no_slide_title" => array("name" => "no_slide_title"),
	"special" => array("name" => "special"),
	"user_only" => array("name" => "user_only"),
	"special_img" => array("name" => "special_img"),
	"no_today" => array("name" => "no_today"),
	"gw_ico" => array("name" => "gw_ico"),
	"gw_img" => array("name" => "gw_img"),
	"gw_title" => array("name" => "gw_title"),
	"gw_content" => array("name" => "gw_content"),
	"gw_link" => array("name" => "gw_link"),
	"tool_ico" => array("name" => "tool_ico"),
	"tool_button" => array("name" => "tool_button"),
	"tool_url" => array("name" => "tool_url"),
	"not_more" => array("name" => "not_more"),
	"button1" => array("name" => "button1"),
	"url1" => array("name" => "url1"),
	"down_doc" => array("name" => "down_doc"),
	"doc_name" => array("name" => "doc_name"),
	"go_direct" => array("name" => "go_direct"),
	"tool_ico_svg" => array("name" => "tool_ico_svg"),
	"gw_ico_svg" => array("name" => "gw_ico_svg"),
	"no_toc" => array("name" => "no_toc"),
	"show_line" => array("name" => "show_line"),
	"toc_four" => array("name" => "toc_four"),
	"allow_copy" => array("name" => "allow_copy"),
	"sub_section" => array("name" => "sub_section"),
	"g_s_c" => array("name" => "g_s_c"),
	"slider_video" => array("name" => "slider_video"),
	"guide_video" => array("name" => "guide_video"),
	"fancy_box" => array("name" => "fancy_box"),
	"poster_img" => array("name" => "poster_img"),
	"sites_des" => array("name" => "sites_des"),
	"sites_url" => array("name" => "sites_url"),
	"taourl_t" => array("name" => "taourl_t"),
	"m_taourl" => array("name" => "m_taourl"),
	"spare_t" => array("name" => "spare_t"),
	"tao_img_t" => array("name" => "tao_img_t"),
	"be_down_name" => array("name" => "be_down_name"),
	"be_file_os" => array("name" => "be_file_os"),
	"be_file_inf" => array("name" => "be_file_inf"),
	"be_down_size" => array("name" => "be_down_size"),
);

function save_one_delete($post_id) {
	global $post, $one_delete;
	foreach ($one_delete as $meta_box) {
		if ( !isset($_POST[$meta_box['name'] . '_noncename']) || !$data = isset($_POST[$meta_box['name'] . '']) ? $_POST[$meta_box['name'] . ''] : null) {
			delete_post_meta($post_id, $meta_box['name'] . '', get_post_meta($post_id, $meta_box['name'] . '', true));
		}
	}
}
add_action('save_post', 'save_one_delete');