/**
 * main
 * Date: 2020/12/28
 *
 * https://wptao.com/wptao.html
 * @author smyx
 * @version 4.4
 *
 **/
function wp_get_aCookie(a){var b,c,d=document.cookie,e=a+"=";if(d){if(c=d.indexOf("; "+e),-1===c){if(c=d.indexOf(e),0!==c)return null}else c+=2;return b=d.indexOf(";",c),-1===b&&(b=d.length),decodeURIComponent(d.substring(c+e.length,b))}}function wp_set_aCookie(a,b,c,d,e,f){if("number"==typeof c){var g=c,h=c=new Date;h.setTime(+h+864e5*g),c=h.toGMTString()}document.cookie=a+"="+encodeURIComponent(b)+(c?"; expires="+c:"")+(d?"; path="+d:"; path=/")+(e?"; domain="+e:"")+(f?"; secure":"")}function wp_clear_aCookie(a,b,c,d){wp_set_aCookie(a,"",-1,b,c,d)}jQuery(function(a){var d,b=(new Date).getTime(),c="";wptaojs.t&&(c="t="+wptaojs.t),wptaojs.cache&&(wptaojs._t&&b/1e3-wptaojs._t>600?c="_t="+wptaojs._t:wptaojs.t&&b/1e3-wptaojs.t>300&&(c="")),c&&a.ajax({type:"GET",url:wptaojs.ajax_url+"?action=wptao_ajax&admininit=0&type=auto&"+c}),a(document).on("click",".uc-copy",function(){var c,d,e,f,g,h,b=a(this).attr("data-text");if(!b)return!1;c=a(this).attr("data-url"),d=a(this).hasClass("go-buy")?1:0,e="uc-copy-text",c&&(b="7👈付致这段话"+b+"转移至👉τao寶👈或點击炼接 "+c+" 至浏.览览.器"),a("#"+e).length>0?a("#"+e).val(b):(f='<textarea id="'+e+'" style="position:absolute;left:-9999px;" readonly="readonly">'+b+"</textarea>",a(this).append(f)),g=document.getElementById(e),g.select(),g.setSelectionRange(0,g.value.length),h=void 0;try{h=document.execCommand("copy")}catch(i){h=!1}return 1===d?h?a(this).html("口令复制成功"):(a(this).hide(),a(this).parent().find("em").removeClass("hide")):a(this).html(h?"复制成功":"复制失败"),!1}),a(".ad_pop_left").show(),a("#ad_pop").length>0&&(wp_get_aCookie("ad_pop")||(d=a("#ad_pop a").attr("href"),-1===location.href.indexOf(d)&&a("#ad_pop").show()),a(".ad_pop_close").click(function(){a("#ad_pop").hide(),wptaojs.pop_num||(wptaojs.pop_num=4),wp_set_aCookie("ad_pop","1",wptaojs.pop_num/24)}))});