<?php
/**
 * Read-only REST API exposure of Thrive Architect post meta.
 *
 * Phase 1 of the Thrive Architect REST Content API: register TCB meta on the
 * standard wp/v2/{post-type} endpoint so external clients (e.g. the CRO Agent)
 * can read post content without writing to it.
 *
 * Auth model
 * ----------
 *   Reads:  Gated by post visibility — WP core already requires `read_post`
 *           on the parent post, so non-public posts return 401/403 before
 *           meta is ever serialised. As defence-in-depth, the
 *           rest_prepare_{post_type} filter additionally nulls TCB meta on
 *           non-public posts when the caller lacks `edit_post`.
 *
 *           (Note: there is no `auth_read_post_meta_*` filter in WP core; the
 *           rest_prepare_* hook is the canonical place to gate per-post REST
 *           data.)
 *
 *   Writes: Blocked at two layers.
 *           1. `auth_callback => '__return_false'` on each meta field — WP
 *              core consults this *after* `current_user_can('edit_post')`,
 *              so the post-meta REST handler rejects the meta write.
 *           2. `rest_pre_insert_{post_type}` strips TCB keys from the
 *              `meta` request param before WP processes it, as a defensive
 *              second line in case any future core change or third-party
 *              filter routes meta writes around the auth_callback gate.
 *
 * Scope: registered on `post` and `page` only for Phase 1 (per plan §6
 * Open Question #5). Filter `tcb_rest_meta_post_types` to extend.
 */

defined( 'ABSPATH' ) || exit;

add_action( 'rest_api_init', 'tcb_rest_meta_register' );

/**
 * Register TCB meta fields as read-only on each in-scope post type.
 *
 * Runs only on rest_api_init so there is zero overhead on admin/frontend loads.
 */
function tcb_rest_meta_register() {
	$meta_definitions = [
		'tve_updated_post' => [
			'type'         => 'string',
			'description'  => 'Thrive Architect HTML content for the post (canonical source for editor-built layouts).',
			'show_in_rest' => true,
		],
		'tve_custom_css' => [
			'type'         => 'string',
			'description'  => 'Inline CSS rules generated by the Thrive Architect editor.',
			'show_in_rest' => true,
		],
		'tve_user_custom_css' => [
			'type'         => 'string',
			'description'  => 'User-authored custom CSS appended to the editor-generated rules.',
			'show_in_rest' => true,
		],
		'tve_globals' => [
			'type'         => 'object',
			'description'  => 'Page-level Thrive Architect settings (font classes, lightbox refs, etc.).',
			'show_in_rest' => [
				'schema'           => [
					'type'                 => 'object',
					'additionalProperties' => true,
				],
				'prepare_callback' => 'tcb_rest_meta_prepare_object_value',
			],
		],
		'tcb2_ready' => [
			'type'         => 'integer',
			'description'  => 'Set to 1 when the post has been migrated to the TCB2 content format.',
			'show_in_rest' => true,
		],
		'tcb_editor_enabled' => [
			'type'         => 'integer',
			'description'  => 'Set to 1 when Thrive Architect is enabled for this post.',
			'show_in_rest' => true,
		],
		'tve_landing_page' => [
			'type'         => 'string',
			'description'  => 'Landing page template key when this post is rendered as a landing page.',
			'show_in_rest' => true,
		],
		'_tve_header' => [
			'type'         => 'string',
			'description'  => 'Custom header symbol ID associated with this post.',
			'show_in_rest' => true,
		],
		'_tve_footer' => [
			'type'         => 'string',
			'description'  => 'Custom footer symbol ID associated with this post.',
			'show_in_rest' => true,
		],
	];

	/**
	 * Filter the post types on which TCB meta is exposed via REST.
	 *
	 * Defaults to `post` and `page` only for v1 — sites that need broader
	 * exposure (e.g. custom CPTs edited with Architect) can extend this list.
	 *
	 * @param string[] $post_types
	 */
	$post_types = apply_filters( 'tcb_rest_meta_post_types', [ 'post', 'page' ] );

	foreach ( $post_types as $post_type ) {
		if ( ! tve_is_post_type_editable( $post_type ) ) {
			continue;
		}

		foreach ( $meta_definitions as $key => $def ) {
			register_post_meta(
				$post_type,
				$key,
				[
					'description'   => $def['description'],
					'show_in_rest'  => $def['show_in_rest'],
					'single'        => true,
					'type'          => $def['type'],
					'auth_callback' => '__return_false',
				]
			);
		}

		add_filter( "rest_prepare_{$post_type}", 'tcb_rest_meta_hide_for_non_public', 10, 3 );
		add_filter( "rest_pre_insert_{$post_type}", 'tcb_rest_meta_block_writes', 10, 2 );
	}
}

/**
 * Strip TCB meta keys from inbound REST write payloads as a belt-and-suspenders
 * write block on top of `auth_callback => __return_false`.
 *
 * The auth_callback already rejects writes via the post-meta REST handler, but
 * stripping the keys here means the request never reaches that path with TCB
 * meta attached — so any future change to how WP core handles meta auth (or any
 * third-party meta-write filter that bypasses auth_callback) cannot regress
 * Phase 1 into accidentally accepting TCB content writes.
 *
 * @param stdClass        $prepared_post Post object prepared from the REST request.
 * @param WP_REST_Request $request       The REST request.
 *
 * @return stdClass
 */
function tcb_rest_meta_block_writes( $prepared_post, $request ) {
	$meta = $request->get_param( 'meta' );

	if ( ! is_array( $meta ) ) {
		return $prepared_post;
	}

	$tcb_keys = [
		'tve_updated_post',
		'tve_custom_css',
		'tve_user_custom_css',
		'tve_globals',
		'tcb2_ready',
		'tcb_editor_enabled',
		'tve_landing_page',
		'_tve_header',
		'_tve_footer',
	];

	$changed = false;
	foreach ( $tcb_keys as $key ) {
		if ( array_key_exists( $key, $meta ) ) {
			unset( $meta[ $key ] );
			$changed = true;
		}
	}

	if ( $changed ) {
		$request->set_param( 'meta', $meta );
	}

	return $prepared_post;
}

/**
 * Coerce object meta values to a JSON-safe shape for REST output.
 *
 * `tve_globals` is stored as a serialized PHP array. WordPress unserialises it
 * on read, but legacy posts can have an empty string stored (or, very rarely,
 * a numerically-indexed array) which trips WP's `object` schema validator.
 * Normalise to an empty object for those cases so the field never errors.
 *
 * @param mixed           $value   Raw meta value (already deserialised by core).
 * @param WP_REST_Request $request Current request (unused).
 * @param array           $args    Meta field args (unused).
 *
 * @return array|stdClass
 */
function tcb_rest_meta_prepare_object_value( $value, $request, $args ) {
	if ( empty( $value ) || ! is_array( $value ) ) {
		return new stdClass();
	}

	// List-shaped arrays JSON-encode as `[]` and fail the `object` schema validator.
	if ( array_keys( $value ) === range( 0, count( $value ) - 1 ) ) {
		return new stdClass();
	}

	return $value;
}

/**
 * Strip TCB meta from REST responses for non-public posts when the caller
 * lacks `edit_post`.
 *
 * Defence-in-depth: WP core already gates draft post access at the controller
 * layer, but this guarantees TCB content never leaks via the meta channel even
 * if a future controller weakens that.
 *
 * @param WP_REST_Response $response REST response object.
 * @param WP_Post          $post     The post being returned.
 * @param WP_REST_Request  $request  The current REST request.
 *
 * @return WP_REST_Response
 */
function tcb_rest_meta_hide_for_non_public( $response, $post, $request ) {
	$is_public = function_exists( 'is_post_publicly_viewable' )
		? is_post_publicly_viewable( $post )
		: ( 'publish' === $post->post_status );

	// Password-protected posts pass `is_post_publicly_viewable()` but their content
	// is not publicly readable — treat them as non-public so TCB meta is stripped
	// for callers who can't `edit_post` (and therefore can't bypass the password).
	if ( ! empty( $post->post_password ) ) {
		$is_public = false;
	}

	if ( $is_public ) {
		return $response;
	}

	if ( current_user_can( 'edit_post', $post->ID ) ) {
		return $response;
	}

	$data = $response->get_data();

	if ( empty( $data['meta'] ) ) {
		return $response;
	}

	$tcb_keys = [
		'tve_updated_post',
		'tve_custom_css',
		'tve_user_custom_css',
		'tve_globals',
		'tcb2_ready',
		'tcb_editor_enabled',
		'tve_landing_page',
		'_tve_header',
		'_tve_footer',
	];

	foreach ( $tcb_keys as $key ) {
		if ( array_key_exists( $key, $data['meta'] ) ) {
			$data['meta'][ $key ] = null;
		}
	}

	$response->set_data( $data );

	return $response;
}
