<div class="tvd-modal-content">
	<p class="tve-duplicate-target-description"></p>

	<div class="tvd-input-field tve-duplicate-select-wrapper">
		<select id="tve-duplicate-target-select" style="width: 100%;">
			<option value=""></option>
		</select>
	</div>

	<p class="tve-no-items-message" style="display: none;"></p>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-modal-close tvd-waves-effect"
			   tabindex="3"><?php echo __( 'Cancel', 'thrive-leads' ) ?></a>
		</div>
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-waves-effect tvd-waves-light tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-dark tvd-right tve-confirm-duplicate tvd-disabled"
			   tabindex="2"><?php echo __( 'Duplicate', 'thrive-leads' ) ?></a>
		</div>
	</div>
</div>
