<hr>
<div class="tl-conversion-tracking">
	<div class="control-grid switch mb-5">
		<div class="fill">
			<span class="switch-label"><#= this.model.config.label #></span>
		</div>
		<div class="tcb-switch tcb-text-right">
			<label>
				<input class="tve-checkbox change" data-fn="check" type="checkbox">
				<span class="tcb-lever"></span>
			</label>
		</div>
	</div>
	<span class="grey-text tl-conversion-description"><#= this.model.config.description #></span>
</div>
