/******* Do not edit this file *******
伍迪广告片段 CSS and JS
Saved: Mar 09 2021 | 00:43:18 */
<script>
(function(){
var el = document.createElement("script");
el.src = "https://sf1-scmcdn-tos.pstatp.com/goofy/ttzz/push.js?6eb4bc3335e4f14577bb0356c4ab0e5b65a0e4eec7e1c5aa41fde8643bb745f2e7e5b183b6eb6a05c2eb7800cf7a0f01d3f157758663fad51e7634e7dfa5a518";
el.id = "ttzz";
var s = document.getElementsByTagName("script")[0];
s.parentNode.insertBefore(el, s);
})(window)
</script>